First Step of Authentication
eriyezab/my-portfolio pull request #19
Opened 2020-06-09 16:26 UTC by eriyezab

Create endpoint to check log in status of users

2020-06-10 21:23 UTC, shrutip90 requested changes

2020-06-10 21:23 UTC, shrutip90 commented on portfolio/src/main/java/com/google/sps/data/Comment.java
> +  public long timestamp() {
Any reason for not using the same convention and calling this getTimestamp?

2020-06-10 21:23 UTC, shrutip90 commented on portfolio/src/main/java/com/google/sps/data/UserStatus.java
> + * <p>Note: The private variables in this class are converted into JSON.
I didn't quite understand this comment. Is the conversion important to mention for some reason? If so, could you please expand the comment to include that.

2020-06-10 21:23 UTC, shrutip90 commented on portfolio/src/main/java/com/google/sps/data/UserStatus.java
> +  private boolean loggedIn;
You can call this isLoggedIn to be more clear.

2020-06-10 21:23 UTC, shrutip90 commented on portfolio/src/main/java/com/google/sps/data/UserStatus.java
> +  public boolean getLoggedIn() {
You can name this isLoggedIn as well. Not sure if the java style guide mentions this. But apparently the general JavaBean specification does: https://stackoverflow.com/questions/1118261/what-is-the-correct-syntax-for-is-variable-getter-setters-in-a-pojo-class

2020-06-10 21:23 UTC, shrutip90 commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    // Check if the user is logged in and if not redirect them. If so get the email
Comments need to be punctuated properly. Please add '.' at the end.

2020-06-10 21:23 UTC, shrutip90 commented on portfolio/src/main/webapp/comments.js
> +const LOG_IN = "Click here to log in: ";
The constant name doesn't look complete. Maybe use LOG_IN_PROMPT or LOG_IN_MESSAGE.

2020-06-10 21:23 UTC, shrutip90 commented on portfolio/src/main/webapp/comments.js
> +const LOG_OUT = "Click here to log out: ";
ditto

2020-06-10 21:23 UTC, shrutip90 commented on portfolio/src/main/webapp/comments.js
> +      }
Can you replace this with an assignment using a ternary operator?

2020-06-10 21:23 UTC, shrutip90 commented on portfolio/src/main/webapp/comments.js
> +    if(userStatus.loggedIn){
How is this code able to access the private variable?

2020-06-11 15:07 UTC, eriyezab commented on portfolio/src/main/webapp/comments.js
> +    if(userStatus.loggedIn){
The UserStatus class is sent from the server as json so I am accessing the loggedIn(now isLoggedIn) member from the json it received. I updated the UserStatus class javadoc/comment to explain it more but let me know if it needs more explanation.

2020-06-16 05:13 UTC, shrutip90 approved these changes

2020-06-16 05:13 UTC, shrutip90 commented on portfolio/src/main/java/com/google/sps/data/Comment.java
> +
You can remove these if they are not intentional - double blank lines at the end of file.

2020-06-16 05:13 UTC, shrutip90 commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    if(USER.isUserLoggedIn()) {
if statement should be followed by a space. See https://google.github.io/styleguide/javaguide.html#s4.6.2-horizontal-whitespace.

2020-06-16 05:13 UTC, shrutip90 commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
>      if(message == null) {
ditto

2020-06-16 05:13 UTC, shrutip90 commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
>      if(sortValue.equals("name")) {
ditto

2020-06-16 05:13 UTC, shrutip90 commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    } else if(sortValue.equals("email")) {
ditto

2020-06-16 05:13 UTC, shrutip90 commented on portfolio/src/main/webapp/comments.js
> +    if(userStatus.isLoggedIn){
ditto

2020-06-16 15:51 UTC, merged